print("Welcome to notebook..")

In [2]:
print("welcome")

welcome


In [4]:
print("Lavasa")

Lavasa


In [5]:
print("shift+enter")

shift+enter


In [5]:
#strings
msg="    This is a string   "
for x in msg:
    print(x,end=",")
#length/number of characters
print("\n")
print(len(msg))
#strip
print("\n")
msg=msg.strip()
print(msg)

 , , , ,T,h,i,s, ,i,s, ,a, ,s,t,r,i,n,g, , , ,

23


This is a string


In [16]:
#for loop
#by counting one
for i in range(1,6,1):
    print(i,end=",")
#by counting two 
print("\n")
for i in range(1,6,2):
    print(i,end=",")

1,2,3,4,5,

1,3,5,

In [1]:
print("printing the list")
listex=["Item 1","Item 2",10,23,45]
print(listex)
#printing list items one by one
print("printing list items one by one")
for i in listex:
    print(i)
#printing each value from list
print("printing each value from list by accessing the index")
print(listex[3])
#print type
print("print type")
print(type(listex))

printing the list
['Item 1', 'Item 2', 10, 23, 45]
printing list items one by one
Item 1
Item 2
10
23
45
printing each value from list by accessing the index
23
print type
<class 'list'>


In [4]:
#functions in string
#split() & strip()
#tab space -"\t" & next line "\n"

a= "\t  hai.. \n"
a=a.strip()
print(a)

hai..


In [16]:
#split - to separate words
a="hello this is a string"
b=a.split(' ') 
print(b)

#if a letter doesnot need just type it in bracket split(); here:-split('is') ,then all the is are removed
a="hello this is a string"
b=a.split('is') 
print(b)

print("\n")
#upper,lower,swapcase
print("joFIn".upper())
print("JOFIN".lower())
print("JoFiN".swapcase())

['hello', 'this', 'is', 'a', 'string']
['hello th', ' ', ' a string']


JOFIN
jofin
jOfIn


In [24]:
#slicing
msg="hellohowareyou"
print(msg[6:13])
print(msg[::-1]) #reverse
print(msg[2:6])

owareyo
uoyerawoholleh
lloh


In [3]:
#typing name and class
name=input("Enter the name:")
nclass=int(input("Enter the class:"))
print("Your name is {} from class {}.".format(name,nclass))

Your name is tony from class 8.


In [7]:
numbers="2,3,5,7,2,8"
n=numbers.split(",")
print(n)
for item in n: #accessing the numbers by calling them as item
    temp=int(item) #converting into integer
    print(item,type(item),temp,type(temp)) #printing the item and its type then again printing type after coverting it into integer

['2', '3', '5', '7', '2', '8']
2 <class 'str'> 2 <class 'int'>
3 <class 'str'> 3 <class 'int'>
5 <class 'str'> 5 <class 'int'>
7 <class 'str'> 7 <class 'int'>
2 <class 'str'> 2 <class 'int'>
8 <class 'str'> 8 <class 'int'>


In [11]:
print(numbers) #finding the sum of numbers above mentioned
s=0
for item in n:
    temp=int(item)
    s=s+temp
print("sum =" ,s)

2,3,5,7,2,8
sum = 27


In [22]:
listex=["one","two","three","four"]
if "two" in listex:
    print("two is found")
listex[1]="TWO"
print(listex)

two is found
['one', 'TWO', 'three', 'four']


In [32]:
newlist=["five","six","seven"] #adding the previous list with new list
newlist.append("eight") #appending to list
new=listex+newlist
print(new)

['TWO', 'four', 'one', 'three', 'five', 'six', 'seven', 'eight']


In [48]:
nlist=["eleven","twelve","thirteen"]
nlist.remove("twelve") #remove accepts strings and numbers
print(nlist)
nlist.append(6)
nlist.remove(6) #pop accepts index value
nlist.append("fourteen")
nlist.sort() #sorting the elements in the list
print(nlist)
nlist.reverse() #reversing
print(nlist)

['eleven', 'thirteen']
['eleven', 'fourteen', 'thirteen']
['thirteen', 'fourteen', 'eleven']


In [1]:
def fun():
    print("Hi I am your first function")
    return("Success",True)
name="jof"
ret=fun()
print(ret)

Hi I am your first function
('Success', True)


1)Define a function that takes a list of numbers as input and return the sum of numbers,without any predefined functions

In [10]:
mylist=[1,3,5,4,2]
def sum(a):
    s=0
    for i in a:
        s=s+i
    return(s)
sum(mylist)


15

2)collect user input with coma separated values

3)Count the number odd and even numbers in the list and print the odd numbers count and even numbers countalong with the numbers (You will have a function that will take a list of numbers,then returns the count of odd numbers and even numbers

FILE HANDLING

In [12]:
file=open("samplefile.txt","w+")

In [13]:
file.write("This is the first line in the file.\nUsing a+ to append and w+ used for writing and if you run again,\nthe stuffs you wrote will be replaced")

138

In [14]:
file.close()

Reading the lines

In [16]:
file_read=open("samplefile.txt","r+")
file_read.readlines() #if it is readline() then it will read only one line

['This is the first line in the file.\n',
 'Using a+ to append and w+ used for writing and if you run again,\n',
 'the stuffs you wrote will be replaced']

Q)Write a function,that accepts your details and save into a file

In [1]:
def details(name,phone,email):
    details=open("mydetails.txt","w+") 
    details.write("name\t:\t",name)
    details.write("\nphone\t:\t",phone)
    details.write("\nEmail\t:\t",email)
    details.close()
    return True
name=input("Name:")
phone=int(input("Phone:"))
email=input("Email:")
ret=details(name,phone,email)
if ret:
    print("Your details are saved..!")
    print("*"*30)
    #for line in open(name+".txt","r+").readline():
file=open(name,".txt","r+")
file_lines = file.readlines()
for line in file_lines:
    print(line)

TypeError: TextIOWrapper.write() takes exactly one argument (2 given)

In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.reshape(3,3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
import pandas as pd

In [18]:
student={
    "Name":["Abhidev SP","John George Thattil","Jaise George","Adharsh Jaison","Amrutha Paalathara"],
    "Age":[18,21,23,34,78]
}
print(student)

{'Name': ['Abhidev SP', 'John George Thattil', 'Jaise George', 'Adharsh Jaison', 'Amrutha Paalathara'], 'Age': [18, 21, 23, 34, 78]}


In [19]:
df=pd.DataFrame(student)

In [20]:
#print(df.head())
print(df.tail())

                  Name  Age
0           Abhidev SP   18
1  John George Thattil   21
2         Jaise George   23
3       Adharsh Jaison   34
4   Amrutha Paalathara   78


In [23]:
df

Name  Age
0           Abhidev SP   18
1  John George Thattil   21
2         Jaise George   23
3       Adharsh Jaison   34
4   Amrutha Paalathara   78